<main>
    <h1><?php echo IT_PROPOS; ?></h1>
    <p>
        Christoph Martin Wieland.
        <br> Ueber die Rechte und Pflichten der Schriftsteller,
        <br> in Absicht ihrer Nachrichten und Urtheile über Nationen, Regierungen und andere öffentliche Gegenstände.
        <br> 1785.
    </p>
    <p>I.
        <br> Freiheit der Presse ist Angelegenheit und Interesse des ganzen Menschengeschlechts. Ihr haben wir hauptsächlich die gegenwärtige Stufe von Cultur und Erleuchtung, worauf der größere Theil der europäischen Völker steht, zu verdanken. Man raube uns diese Freiheit, so wird das Licht, dessen wir uns gegenwärtig erfreuen, bald wieder verschwinden; Unwissenheit wird bald wieder in Dummheit ausarten, und Dummheit uns wieder dem Aberglauben und dem Despotismus preisgeben. Die Völker werden in die Barbarei der finstern Jahrhunderte zurück sinken; und wer sich dann erkühnen wird, Wahrheiten zu sagen, an deren Verheimlichung den Unterdrückern der Menschheit gelegen ist, wird ein Ketzer und Aufrührer heißen und als ein Verbrecher bestraft werden.</p>

    <p>
        II.
        <br> Freiheit der Presse ist nur darum ein Recht der Schriftsteller, weil sie ein Recht der Menschheit oder, wenn man will, ein Recht policirter Nationen ist; und sie ist blos darum ein Recht des Menschengeschlechts, weil die Menschen, als vernünftige Wesen, kein angelegeneres Interesse haben, als wahre Kenntnisse von Allem, was auf irgend eine Art geradezu oder seitwärts einen Einfluß auf ihren Wohlstand hat und zu Vermehrung ihrer Vollkommenheit etwas beitragen kann.</p>

    <p>
        III.
        <br> Die Wissenschaften, welche für den menschlichen Verstand das sind, was das Licht für unsere Augen, können und dürfen also ohne offenbare Verletzung eines unleugbaren Menschenrechtes in keine andere Grenzen eingeschloßen werden, als diejenigen, welche uns die Natur selbst gesetzt hat. Alles, was wir wissen können, das dürfen wir auch wissen.</p>

    <p>
        IV.
        <br> Die nöthigste und nützlichste aller Wissenschaften oder, noch genauer zu reden, diejenige, in welcher alle übrige eingeschlossen sind, ist die Wissenschaft des Menschen:
        <br>

        <em>Der Menschheit eignes Studium ist der Mensch.</em>
        <br> Sie ist eine Aufgabe, an deren vollständiger und reiner Auflösung man noch Jahrtausende arbeiten wird, ohne damit zu Stande gekommen zu seyn. Sie anzubauen, zu fördern, immer größere Fortschritte darin zu thun, ist der Gegenstand des Menschenstudiums; und wie könnte dieses auf andere Weise mit Erfolge getrieben werden, als indem man die Menschen, wie sie von jeher waren, und wie sie dermalen sind, nach allen ihren Beschaffenheiten, Verhältnissen und Umständen kennen zu lernen sucht?</p>

    <p>
        V.
        <br> Diese historische Kenntniß der vernünftigen Erdebewohner ist die Grundlage aller echt philosophischen Wissenschaft, welche die Natur und Bestimmung des Menschen, seine Rechte und seine Pflichten, die Ursachen seines Elendes und die Bedingungen seines Wohlstandes, die Mittel, jenes zu mindern und diesen zu befördern, kurz, das allgemeine Beste des menschlichen Geschlechtes zum Gegenstande hat. Um heraus zu bringen, was dem Menschen möglich ist, muß man wissen, was er wirklich ist und wirklich geleistet hat. Um seinen Zustand zu verbessern und seinen Gebrechen abzuhelfen, muß man erst wissen, wo es ihm fehlt, und, woran es liegt, daß es nicht besser um ihn steht. Im Grunde ist also alle echte Menschenkenntniß historisch. Die Geschichte der Völker, nach ihrer ehemaligen und gegenwärtigen Beschaffenheit, in derjenigen Verbindung der Thatsachen und Begebenheiten, woraus man sieht, wie sie zusammen hangen, und wie die Wirkung oder der Erfolg des Einen wieder die Veranlassung oder Ursache des Andern wird – diese Philosophie der Menschengeschichte ist nichts Anderes, als Darstellung dessen, was sich mit den Menschen zugetragen und immerfort zuträgt; Darstellung eines immer fortlaufenden Factums, wozu man nicht anders gelangen kann, als indem man die Augen aufmacht und sieht, und indem diejenigen, welche mehr Gelegenheit als alle Andere gehabt haben, zu sehen, was zu sehen ist, ihre Beobachtungen den Andern mittheilen.</p>

    <p>
        VI.
        <br> Aus diesem Gesichtspunkte sind alle Beiträge zu beurtheilen, welche von verständigen und erfahrenen Männern, von Seefahrern und Landfahrern, Reisigen und Fußgängern, Gelehrten und Ungelehrten (denn auch Ungelehrte können den Geist der Beobachtung haben und sehen oft aus gesundern Augen als Gelehrte von Profession) zur Erd- und Völkerkunde oder, mit einem Wort, zur Menschenkenntniß in größern oder kleinern Bruchstücken bekannt gemacht worden sind. Ans diesem Gesichtspunkte erkennt man ihre Schätzbarkeit und daß dem menschlichen Geschlecht überhaupt und jedem Volke, jedem einzelnen Staatskörper und jedem einzelnen Menschen insbesondere daran gelegen ist, daß solcher Beiträge recht viele in dem allgemeinen Magazine der menschlichen Kenntnisse niedergelegt werden.</p>

    <p>
        VII.
        <br> Insonderheit ist jedem großen Volke – und ganz vorzüglich dem unsrigen (dessen Staatskörper eine so sonderbare Gestalt hat und aus so mannigfaltigen und ungleichartigen Theilen mehr zufälliger Weise zusammen gewachsen, als planmäßig zusammen gesetzt ist), daran gelegen, seinen gegenwärtigen Zustand so genau als möglich zu kennen. Jeder noch so geringe Beitrag, der über die Beschaffenheit der Staatswirthschaft, Polizei, bürgerlichen und militärischen Verfassung, Religion, Sitten, öffentlichen Erziehung, Wissenschaften und Künste, Gewerbe, Landwirthschaft u. s. w. in jedem Theile unseres gemeinsamen Vaterlandes und über die Stufe der Cultur, Aufklärung, Humanisirung, Freiheit, Thätigkeit und Emporstrebung zum Bessern, die jeder derselben erreicht hat, einiges Licht verbreitet, jeder solche Beitrag ist schätzbar und verdient unsern Dank.</p>

    <p>
        VIII.
        <br> Die erste und wesentlichste Eigenschaft eines Schriftstellers, welcher einen Beitrag zur Menschen- und Völkerkunde aus eigener Beobachtung liefert, ist: daß er den aufrichtigen Willen habe, die Wahrheit zu sagen, folglich keiner Leidenschaft, keiner vorgefaßten Meinung, keiner interessirten Privatabsicht wissentlich einigen Einfluß in seine Nachrichten und Bemerkungen erlaube. Seine erste Pflicht ist Wahrhaftigkeit und Unparteilichkeit: und da wir zu Allem berechtigt sind, was eine nothwendige Bedingung der Erfüllung unsrer Pflicht ist; so ist auch, vermöge der Natur der Sache, Freimüthigkeit ein Recht, das keinem Schriftsteller dieser Classe streitig gemacht werden kann. Er muß die Wahrheit sagen wollen und sagen dürfen.</p>

    <p>
        IX.
        <br> Diesemnach ist ein Schriftsteller vollkommen berechtigt, von dem Volke, über welches er uns seine Beobachtungen mittheilt, Alles zu sagen, was er gesehen hat, Gutes und Böses, Rühmliches und Tadelhaftes. Mit ungetreuen Gemälden, welche nur die schöne Seite darstellen und die fehlerhafte entweder ganz verdunkeln oder gar durch schmeichlerische Verschönerung verfälschen, ist der Welt nichts gedient.</p>

    <p>
        X.
        <br> Niemand kann sich beleidigt halten, wenn man ihn abschildert, wie er ist. Die Höflichkeit, welche uns verbietet, einer Person in öffentlicher Gesellschaft ihre Fehler zu sagen, ist keine Pflicht des Schriftstellers, der vom Menschen überhaupt oder von Nationen, Staaten und Gemeinheiten (wie groß oder klein sie übrigens seyn mögen) zu sprechen hat. Eine Nation würde etwas Unbilliges verlangen und sich lächerlich vor der Welt machen, welche für ganz untadelig und von allen Seiten vollkommen gehalten seyn wollte; und ganz untadelig müßte sie doch seyn, wenn ein verständiger Beobachter gar nichts an ihr auszusetzen hätte. Alles, was in solchem Falle die Ehrerbietung gegen eine ganze Nation oder Gemeinheit fordert, ist, in anständigen Ausdrücken, ohne Uebertreibung, Bitterkeit und Muthwillen von ihrer blinden Seite zu sprechen und vornehmlich seine Unparteilichkeit auch dadurch zu beweisen, daß man ihren Vorzügen und Allem, was an ihr zu rühmen ist, Gerechtigkeit widerfahren lasse.</p>

    <p>
        XI.
        <br> Zu Erlangung einer richtigen Kenntniß von Nationen und Zeitaltern ist hauptsächlich vonnöthen, daß man das Unterscheidende oder Charakteristische eines jeden Volkes, welches merkwürdig genug ist, um die öffentliche Aufmerksamkeit zu verdienen, kennen lerne. Dieses Charakteristische äußert sich gewöhnlich eben sowohl, ja oft noch stärker und auszeichnender, in Fehlern, als in Vollkommenheiten. Oft sind die Fehler nur ein Uebermaß von gewissen Eigenschaften, die in gehörigem Maße sehr löblich sind, wie zum Beispiel geziertes Wesen ein Uebermaaß von Eleganz ist. Nicht selten sind die Fehler an Nationen, eben so wie an einzelnen Menschen, blos natürliche (wiewohl allezeit verbesserliche) Folgen eben derjenigen Sinnesart, wodurch ein Volk zu gewissen Tugenden besonders aufgelegt ist, wie zum Beispiel die Nationaleitelkeit des französischen Volkes ein Fehler ist, den es nicht hätte, wenn nicht hohes Ehrgefühl, Liebe zum Ruhm und lebhafte Theilnehmung an Nationalehre Hauptzüge seines Charakters wären. Fehler dieser Art bemerken heißt nicht beleidigen, sondern einen Dank verdienenden Wink geben, wo und wie man in seiner Art besser und lobenswürdiger werden kann.</p>

    <p>
        XII.
        <br> Ein unbefangener Beobachter, den die Natur mit Scharfsinn und Lebhaftigkeit des Geistes ausgesteuert, und die Philosophie mit dem richtigen Maßstabe dessen, was löblich, schön, anständig und schicklich oder das Gegentheil ist, versehen hat, sieht überall, wo er hinkommt, die Menschen und ihr Thun und Lassen, ihre Gewohnheiten und Eigenheiten, Schiefheiten und Albernheiten in ihrem natürlichen Lichte; und, ohne die mindeste Absicht, etwas lächerlich machen zu wollen, findet sich, daß man über das Lächerliche – lachen oder lächeln muß. Wohl dem Volke, das nur lächerliche Fehler hat!</p>

    <p>
        XIII.
        <br> Zuweilen liegt der vermeinte Tadel, worüber man sich unzeitig beklagt, blos in der Vorstellungsart einer übermäßig reizbaren Selbstgefälligkeit. Als Xenophon seine zwei Gemälde von der spartanischen und athenischen Republik gegen einander stellte, schrieen die Athener, welche gewohnt waren, von ihren Sophisten und Lobrednern immer nur schmeichelhafte Dinge zu hören, über großes Unrecht; aber wir, die keinen Grund haben, weder Athenern noch Spartanern zu schmeicheln oder mehr Vorliebe für die Einen als für die Andern zu haben, wir finden, daß Xenophon den Athenern kein Unrecht that. Er sagt mit der ihm ganz eigenen Simplicität und Geradheit, was Jedermann, der nach Athen ging und mit seinen eigenen Augen sah, sehen mußte. Die Athener schrieen über Satire und Ironie, wo Xenophon weder an Satire noch Ironie gedacht hatte. Die Wahrheit war, daß er sie blos in einen Spiegel schauen ließ. Sein Gemälde ist das Gemälde einer jeden Republik, in welcher das Volk die höchste Gewalt hat; und alle die besondern Züge, die nur auf die Athener zu passen scheinen, sind im Grunde bloße Modificationen, wovon der nähere Grund in ihrer Lage und in ihren äußern Umständen zu finden war. Ich kann die Verfassung der Athener nicht loben, sagt Xenophon; aber, da es ihnen einmal beliebt hat, sich eine solche Verfassung zu geben, so finde ich, daß sie sehr inconsequent seyn müßten, wenn sie anders wären, als sie sind. Man tadelt dieß und dieß und dieß an ihnen und überlegt nicht, daß sie, ihre Staatsverfassung vorausgesetzt, in Allem dem, weßwegen man sie tadelt, Recht haben. Sein Buch von der athenischen Republik ist daher, wenn man will, eine Satire und eine Apologie zu gleicher Zeit; in der That aber weder mehr noch weniger als eine historische Darstellung dessen, was die Athener in ihrer demokratischen Epoche waren, in ein solches Licht gestellt, daß man deutlich begreift, wie sie das waren, und warum sie es waren, und warum es unmöglich war, daß sie anders hätten seyn sollen, solange sie nicht die Quelle Alles dessen, was an ihnen tadelhaft war, ihre Verfassung, änderten.
        <br> Eine eben so simple, eben so getreue und ungeschmeichelte Darstellung dessen, was in unserm gegenwärtigen Zeitmomente jeder besondere Staat, jede große oder kleine Haupt-Residenz und freie Reichsstadt in Deutschland wirklich ist, wie jene Xenophontische von Sparta und Athen, würde ihrem Verfasser zwar wahrscheinlich viel Verdruß und keine öffentliche Danksagung im Namen Kaisers und Reichs zuziehen (wie ehedem Doctor Burnet für seine Whiggische Geschichte von England vom Ober- und Unterhause des großbritannischen Parlaments erhielt), aber er würde eine solche Danksagung wenigstens verdienen; denn es wäre eine große Wohlthat, die er der Nation erwiese.</p>

    <p>
        XIV.
        <br> Wer aus einem großen Staat in einen andern kommt, worin Verfassung und Einrichtung, Nationalcharakter und Nationalsitten mit jenem stark abstechen, zum Beispiel aus einem militärischen in einen, der seinen Wohlstand dem Frieden und den Künsten des Friedens zu danken hat, der bringt eine Disposition mit sich, vorzüglich Alles das zu bemerken, was den Unterschied zwischen beiden ausmacht, weil dieß gerade die Züge sind, die ihm am stärksten auffallen. Daher kommt es denn ganz natürlich, daß er ein Belieben daran findet, das Charakteristische der einen und der andern Nation gegen einander zu stellen und mit einander zu vergleichen – ein Verfahren, wodurch gemeiniglich heraus kommt, daß das, worin die eine sich besonders hervor thut, gerade nicht die glänzendste Seite der andern ist. Kein Volk, zumal ein kleines, kann alle mögliche Vorzüge beisammen haben; es gibt sogar einige, die einander ausschließen. Ich bin gewiß, daß ein Haufen edler junger Mitbürger und Cameraden des Alcibiades, ihrer Tapferkeit unbeschadet, gegen eben so viele spartanische Knasterbärte wie ein Trupp schöner Herren, die zum Tanze gehen, aussahen. Spartaner und Athener, Thebaner und Korinther (alte oder moderne) in einem Gemälde gegen einander contrastiren zu lassen, ist immer eine sehr unschuldige Sache, wiewohl die Einen auf die Andern wechselsweis ein nicht immer vortheilhaftes Licht werfen.</p>

    <p>
        XV.
        <br> Was von Nationen gesagt worden, gilt auch von Regenten und großen Herren. August und Trajan, wenn man ihren Schmeichlern und Lobrednern glauben wollte, müßten keine Menschen, sondern Götter und Ideale aller Vollkommenheiten gewesen seyn. Eben so, wenn man den Büchermachern in ihren Zueignungsschriften und den Zeitungsschreibern, wenn sie Todesfälle und Thronbesteigungen ankündigen, und den Leichenpredigern oder Standrednern, wenn sie aus bezahlter Pflicht zum letztenmale loben, unbeschränkt glauben müßte; so wären alle unsere Regenten, vom ersten Monarchen in Europa bis zum kleinsten aller Dynasten im heiligen römischen Reiche, lauter Auguste und Trajane. Wollte Gott! Aber was ist – ist; und wie es überall in der Welt ist, das sieht, wer ein Paar gesunde Augen hat, und, wer nicht sehen kann, fühlt's. Regenten, die von ihrer Würde und von ihrem Amte die gehörige Empfindung haben, verachten solche Schmeicheleien und wissen, daß, wer das Herz hat, ihnen unangenehme Wahrheiten zu sagen, es gewiß ehrlich mit ihnen meint. Der beste Fürst ist der, dessen größter Wunsch ist, der beste Mensch unter seinem Volke zu seyn. Und gewiß, ein solcher kann und wird es nicht übel finden, wenn man ihm mit Bescheidenheit zu verstehen gibt, was die Nachwelt ohne Scheu heraus sagen wird, wenn es zu spät für ihn seyn wird, Nutzen daraus zu ziehen.</p>

    <p>
        XVI.
        <br> So wie es keinen wissenschaftlichen Gegenstand gibt, den man nicht untersuchen, ja selbst keinen Glaubenspunkt, den die Vernunft nicht beleuchten dürfte, um zu sehen, ob er glaubwürdig sey oder nicht: so gibt es auch keine historische und keine praktische Wahrheit, die man mit einem Interdict zu belegen oder für Contrebande zu erklären berechtigt wäre. Es ist widersinnig, Staatsgeheimnisse aus Dingen machen zu wollen, die aller Welt vor Augen liegen, oder übel zu nehmen, wenn Jemand der ganzen Welt sagt, was einige hunderttausend Menschen sehen, hören und fühlen.</p>

    <p>
        XVII.
        <br> Ein Augenzeuge kann, ohne Schuld seines Willens, unrichtig sehen. Wer einem Andern, den er für glaubwürdig hält, etwas nachsagt, kann falsch berichtet worden seyn. Der aufmerksamste und scharfsinnigste Beobachter ist, wie alle Menschen, der Möglichkeit des Irrthums unterworfen und kann einen wichtigen Umstand übersehen oder Manches nicht aus seinem wahren Gesichtspunkt oder in dem gehörigsten Lichte gesehen haben. Es ist also kaum möglich, daß Schriften, worin Völker, Staaten, merkwürdige Menschen und Begebenheiten, Sitten der Zeit und dergleichen historisch geschildert werden, selbst bei dem reinsten Vorsatze, die Wahrheit zu sagen, von allen Unrichtigkeiten gänzlich frei seyn sollten. Auch ist es möglich, daß Jemand aus Unerfahrenheit oder Beschränktheit seiner Einsichten oder aus dunkeln Vorstellungen und Neigungen, die ohne sein Wissen auf seinen Willen wirken (zum Beispiel aus Vorliebe für sein eignes Vaterland), zuweilen unrichtig sehen und urtheilen kann. Aber es wäre widersinnig, den Schluß hieraus zu ziehen, daß man also keine historische Schriften, keine Beiträge zur Völker- und Menschenkunde, keine Reisebeschreibungen und keine Sammlungen solcher Thatsachen, deren Publicität der Welt nützlich ist oder werden kann, mehr bekannt machen dürfe. Alles, was daraus folgt, ist, daß ein Jeder, der die Sache besser zu wissen glaubt oder die Irrthümer eines Schriftstellers aufzudecken und zu berichtigen im Stande ist, nicht nur volle Befugniß, sondern sogar eine Art von Pflicht auf sich hat, der Welt damit zu dienen.</p>


</main>